### ISSUE TITLE
Incompatible package version in `environment_checklist.sh`

### ISSUE THREAD

**Issue by flyingcat047** [fedlearnAI/fedlearn-algo#16]
Problem:
The intel-numpy package is incompatible with pandas package which are installed by running the file `environment_checklist.sh`

Details:
The version of the installed intel-numpy is 1.15.1. The version of the installed pandas package is incompatible with numpy < 1.15.4

Reproduce the error:
1. Under the environment of Python 3.6.13
2. Go to the root repository of `fedlearn-algo`
3. Install the python packages by running `./environment_checklist.sh`
4. See this error when running command `python demos/random_forest/client.py -I 0 -C demos/random_forest/config.py`

**Comment by guabao** [comment]
The reason is that intel no longer supports single distribution of numpy/scipy with intel MKL.

We update the checklist in #17 to avoid the problem.

For users that would like to get the best performance, we suggest using numpy/scipy built with intel MKL.
There are several ways to get numpy/scipy with MKL. For example, one can get it from [intel distribution for python](https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/distribution-for-python.html#gs.av4cnp) or one can use anaconda which has a built-in runtime of MKL.

**Comment by guabao** [comment]
I will close this issue. Feel free the reopen it if you still have this issue after updating the repo.
